Repository XtremeOwnage/rPDU2MQTT, pull requests merged in 2024-09, with the labels that each got.

#24 Round 2
  .gitignore
  rPDU2MQTT/Classes/Config.cs
  rPDU2MQTT/Classes/MQTTServiceDependancies.cs
  rPDU2MQTT/Classes/PDU.cs
  rPDU2MQTT/Extensions/EntityWithName_Overrides.cs
  rPDU2MQTT/Extensions/IEntityWithState_Extensions.cs
  rPDU2MQTT/Extensions/RootData_Extensiosn.cs
  rPDU2MQTT/Helpers/DefaultNames.cs
  rPDU2MQTT/Helpers/MeasurementHelper.cs
  rPDU2MQTT/Helpers/ThrowError.cs
  rPDU2MQTT/Models/Config/ActionsConfig.cs
  rPDU2MQTT/Models/Config/Config.cs
  rPDU2MQTT/Models/Config/HomeAssistantConfig.cs
  rPDU2MQTT/Models/Config/MQTTConfig.cs
  rPDU2MQTT/Models/Config/Overrides.cs
  rPDU2MQTT/Models/Config/PduConfig.cs
  rPDU2MQTT/Models/Config/Schemas/Connection.cs
  rPDU2MQTT/Models/Config/Schemas/Credentials.cs
  rPDU2MQTT/Models/Config/Schemas/EntityOverride.cs
  rPDU2MQTT/Models/Config/TypeOverride.cs
  rPDU2MQTT/Models/HomeAssistant/DiscoveryTypes/SensorDiscovery.cs
  rPDU2MQTT/Models/HomeAssistant/Enums/DeviceClass.cs
  rPDU2MQTT/Models/HomeAssistant/baseClasses/baseEntity.cs
  rPDU2MQTT/Models/PDU/Device.cs
  rPDU2MQTT/Models/PDU/RootData.cs
  rPDU2MQTT/Program.cs
  rPDU2MQTT/Services/HomeAssistantDiscoveryService.cs
  rPDU2MQTT/Services/MQTTPublishingService.cs
  rPDU2MQTT/Services/baseTypes/baseDiscoveryService.cs
  rPDU2MQTT/Services/baseTypes/baseMQTTTService.cs
  rPDU2MQTT/Services/baseTypes/basePublishingService.cs
  rPDU2MQTT/Startup/ConfigLoader.cs
  rPDU2MQTT/Startup/FindYamlConfig.cs
  rPDU2MQTT/Startup/ServiceConfiguration.cs
  rPDU2MQTT/appsettings.json
  rPDU2MQTT/config.defaults.yaml
  rPDU2MQTT/rPDU2MQTT.csproj
Labels: lifecycle/active, triage/accepted, kind/cleanup, priority/high, kind/feature

#30 Implements #29 - Ability to disable certificate validation
  rPDU2MQTT/Models/Config/Schemas/Connection.cs
  rPDU2MQTT/Startup/ServiceConfiguration.cs
  rPDU2MQTT/config.defaults.yaml
Labels: lifecycle/active, triage/accepted, priority/normal, kind/feature

#32 Added "Debug" Configuration
  rPDU2MQTT/Models/Config/Config.cs
  rPDU2MQTT/Models/Config/DebugConfig.cs
  rPDU2MQTT/Services/baseTypes/baseDiscoveryService.cs
  rPDU2MQTT/Services/baseTypes/baseMQTTTService.cs
  rPDU2MQTT/config.defaults.yaml
Labels: kind/support, lifecycle/active, triage/accepted, priority/normal, kind/feature

#33 Correct NullReferenceExceptions
  rPDU2MQTT/Classes/PDU.cs
  rPDU2MQTT/Extensions/EntityWithName_Overrides.cs
  rPDU2MQTT/Helpers/StringHelper.cs
  rPDU2MQTT/Models/Config/MQTTConfig.cs
  rPDU2MQTT/Models/Config/Overrides.cs
Labels: kind/bug, lifecycle/active, priority/normal

#34 Better Logging
  .gitignore
  rPDU2MQTT/Classes/PDU.cs
  rPDU2MQTT/Helpers/ThrowError.cs
  rPDU2MQTT/Models/Config/Config.cs
  rPDU2MQTT/Models/Config/LoggingConfig.cs
  rPDU2MQTT/Models/Config/Schemas/FileLoggingTargetConfiguration.cs
  rPDU2MQTT/Models/Config/Schemas/LoggingTargetConfiguration.cs
  rPDU2MQTT/Program.cs
  rPDU2MQTT/Services/HomeAssistantDiscoveryService.cs
  rPDU2MQTT/Services/MQTTPublishingService.cs
  rPDU2MQTT/Services/baseTypes/baseDiscoveryService.cs
  rPDU2MQTT/Services/baseTypes/baseMQTTTService.cs
  rPDU2MQTT/Services/baseTypes/basePublishingService.cs
  rPDU2MQTT/Startup/ConfigLoader.cs
  rPDU2MQTT/Startup/ConfigureLogging.cs
  rPDU2MQTT/Startup/ServiceConfiguration.cs
  rPDU2MQTT/Startup/YamlConfigLoader.cs
  rPDU2MQTT/appsettings.json
  rPDU2MQTT/config.defaults.yaml
  rPDU2MQTT/globalusings.cs
  rPDU2MQTT/rPDU2MQTT.csproj
Labels: lifecycle/active, priority/normal, kind/feature

#35 V0.2.1 - Bug Fixes, and Better Logging
  .gitignore
  rPDU2MQTT/Classes/PDU.cs
  rPDU2MQTT/Extensions/EntityWithName_Overrides.cs
  rPDU2MQTT/Helpers/StringHelper.cs
  rPDU2MQTT/Helpers/ThrowError.cs
  rPDU2MQTT/Models/Config/Config.cs
  rPDU2MQTT/Models/Config/DebugConfig.cs
  rPDU2MQTT/Models/Config/LoggingConfig.cs
  rPDU2MQTT/Models/Config/MQTTConfig.cs
  rPDU2MQTT/Models/Config/Overrides.cs
  rPDU2MQTT/Models/Config/Schemas/FileLoggingTargetConfiguration.cs
  rPDU2MQTT/Models/Config/Schemas/LoggingTargetConfiguration.cs
  rPDU2MQTT/Program.cs
  rPDU2MQTT/Services/HomeAssistantDiscoveryService.cs
  rPDU2MQTT/Services/MQTTPublishingService.cs
  rPDU2MQTT/Services/baseTypes/baseDiscoveryService.cs
  rPDU2MQTT/Services/baseTypes/baseMQTTTService.cs
  rPDU2MQTT/Services/baseTypes/basePublishingService.cs
  rPDU2MQTT/Startup/ConfigLoader.cs
  rPDU2MQTT/Startup/ConfigureLogging.cs
  rPDU2MQTT/Startup/ServiceConfiguration.cs
  rPDU2MQTT/Startup/YamlConfigLoader.cs
  rPDU2MQTT/appsettings.json
  rPDU2MQTT/config.defaults.yaml
  rPDU2MQTT/globalusings.cs
  rPDU2MQTT/rPDU2MQTT.csproj
Labels: kind/bug, lifecycle/active, triage/accepted, kind/cleanup, priority/normal, kind/feature

#38 Fix- Empty dictionary causes null reference exception.
  rPDU2MQTT/Startup/YamlConfigLoader.cs
Labels: kind/bug, triage/accepted, lifecycle/new

#39 V0.2.2
  Examples/Configuration/config.spec.yaml
  Examples/Configuration/minimum-configuration-example.yaml
  Examples/Configuration/recommended-configuration.yaml
  Examples/Docker-Compose/README.md
  Examples/Docker-Compose/docker-compose.yaml
  Examples/Kubernetes/configuration.yaml
  Examples/Kubernetes/deployment.yaml
  Examples/Kubernetes/exec
  Examples/Kubernetes/manifests.yaml
  Examples/Kubernetes/namespace.yaml
  Examples/Kubernetes/restart
  README.md
  docs/Configuration.md
  docs/Deployment.md
  rPDU2MQTT/Startup/YamlConfigLoader.cs
  rPDU2MQTT/rPDU2MQTT.csproj
Labels: kind/bug, kind/documentation, kind/support, triage/accepted, priority/normal, area/deployment/kubernetes, lifecycle/new, area/deployment/docker-compose, area/documentation

#41 V0.3.0
  Examples/Configuration/config.spec.yaml
  Examples/unRAID/README.md
  docs/Deployment.md
Labels: kind/documentation, lifecycle/new, area/deployment/docker-compose

#42 #15 - Retain Discovery Messages
  Examples/Configuration/config.spec.yaml
  rPDU2MQTT/Models/Config/HomeAssistantConfig.cs
  rPDU2MQTT/Services/baseTypes/baseDiscoveryService.cs
  rPDU2MQTT/Services/baseTypes/baseMQTTTService.cs
Labels: lifecycle/active, triage/accepted, priority/high, kind/feature

#44 v0.3.0
  Examples/Configuration/config.spec.yaml
  rPDU2MQTT/Classes/MqttEventHandler.cs
  rPDU2MQTT/Classes/TaskManager.cs
  rPDU2MQTT/Models/Config/HomeAssistantConfig.cs
  rPDU2MQTT/Program.cs
  rPDU2MQTT/Services/baseTypes/baseDiscoveryService.cs
  rPDU2MQTT/Services/baseTypes/baseMQTTTService.cs
  rPDU2MQTT/Startup/ServiceConfiguration.cs
Labels: kind/bug, lifecycle/active, priority/normal, kind/feature
